spring:
  profiles:
    active: dev
  elasticsearch:
    rest:
      uris: www.zealot.group:9200

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: www.zealot.group:9300