spring:
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://www.zealot.group:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: zealot
      password: zealot
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
#      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /druid
  tomcat:
    uri-encoding: UTF-8